### PR TITLE
Connect oeh and hcrt

### PR DESCRIPTION
**Pull request by lummerland**
Hi @sroertgen, 

I would like to map the relationships of the learning resource type vocabs in OEH and the HCRT. As far as I know the way to do so is via `skos:*Match`, right? If so I would like to complete the proposal here and open a PR to integrate this in the public project. Maybe we can talk about it next week :)

Best,
Manuel

### CODE REVIEW

**Comment by lummerland** [comment]
This is a comparison of all concepts as far as I can tell. How do we handle missing matches?

| HCRT                                                        | OEHRT                                                                                                                                                 |
| ----------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------- |
| [Softwareanwendung](https://w3id.org/kim/hcrt/application)  | [Anwendung/Software](http://w3id.org/openeduhub/vocabs/learningResourceType/application)                                                              |
| [Lernkontrolle](https://w3id.org/kim/hcrt/assessment)       | [Lernkontrolle](https://vocabs.openeduhub.de/w3id.org/openeduhub/vocabs/learningResourceType/assessment.html)                                         |
| [Audio](https://w3id.org/kim/hcrt/audio)                    | [Audio](http://w3id.org/openeduhub/vocabs/learningResourceType/audio)                                                                                 |
| [Video](https://w3id.org/kim/hcrt/video)                    | [Video](http://w3id.org/openeduhub/vocabs/learningResourceType/video)                                                                                 |
| [Fallstudie](https://w3id.org/kim/hcrt/case_study)          | [Fallstudie](http://w3id.org/openeduhub/vocabs/learningResourceType/case_study)                                                                       |
| [Kurs](https://w3id.org/kim/hcrt/course)                    | [Kurs](http://w3id.org/openeduhub/vocabs/learningResourceType/course)                                                                                 |
| [Daten](https://w3id.org/kim/hcrt/data)                     | [Daten](http://w3id.org/openeduhub/vocabs/learningResourceType/data)                                                                                  |
| [Übung](https://w3id.org/kim/hcrt/drill_and_practice)       | [Übung](http://w3id.org/openeduhub/vocabs/learningResourceType/drill_and_practice)                                                                    |
| [Lernspiel](https://w3id.org/kim/hcrt/educational_game)     | [Lernspiel](http://w3id.org/openeduhub/vocabs/learningResourceType/educational_game)                                                                  |
| [Experiment](https://w3id.org/kim/hcrt/experiment)          | [Experiment](http://w3id.org/openeduhub/vocabs/learningResourceType/experiment)                                                                       |
| [Abbildung](https://w3id.org/kim/hcrt/image)                | [Bild](http://w3id.org/openeduhub/vocabs/learningResourceType/image) & [Foto](http://w3id.org/openeduhub/vocabs/learningResourceType/photograph)      |
| [Nachschlagewerk](https://w3id.org/kim/hcrt/index)          | [Glossar](http://w3id.org/openeduhub/vocabs/learningResourceType/glossary) & [Handbuch](http://w3id.org/openeduhub/vocabs/learningResourceType/guide) |
| [Unterrichtsplanung](https://w3id.org/kim/hcrt/lesson_plan) | [Unterrichtsplanung](http://w3id.org/openeduhub/vocabs/learningResourceType/lesson_plan)                                                              |
| [Karte](https://w3id.org/kim/hcrt/map)                      | [Karte](http://w3id.org/openeduhub/vocabs/learningResourceType/map)                                                                                   |
| [Fragebogen](https://w3id.org/kim/hcrt/questionnaire)       | [Recherche-Auftrag](http://w3id.org/openeduhub/vocabs/learningResourceType/enquiry_oriented_activity)                                                 |
| [Simulation](https://w3id.org/kim/hcrt/simulation)          | [Simulation](http://w3id.org/openeduhub/vocabs/learningResourceType/simulation)                                                                       |
| [Präsentation](https://w3id.org/kim/hcrt/slide)             | [Präsentation](http://w3id.org/openeduhub/vocabs/learningResourceType/presentation)                                                                   |
| [Textdokument](https://w3id.org/kim/hcrt/text)              | [Text](http://w3id.org/openeduhub/vocabs/learningResourceType/text)                                                                                   |
| [Sonstiges](https://w3id.org/kim/hcrt/other) ❓             | [Anderes Material](http://w3id.org/openeduhub/vocabs/learningResourceType/other_asset_type)                                                           |
| [Webseite](https://w3id.org/kim/hcrt/web_page)              | [Website](http://w3id.org/openeduhub/vocabs/learningResourceType/web_page)                                                                            |
| [Sonstiges](https://w3id.org/kim/hcrt/other)                | [Andere Resource](http://w3id.org/openeduhub/vocabs/learningResourceType/other)                                                                       |
| [Diagramm](https://w3id.org/kim/hcrt/diagram)               | ❓                                                                                                                                                    |
| [Portal](https://w3id.org/kim/hcrt/portal)                  | ❓                                                                                                                                                    |
| [Skript](https://w3id.org/kim/hcrt/script)                  | ❓                                                                                                                                                    |
| [Musiknoten](https://w3id.org/kim/hcrt/sheet_music)         | ❓                                                                                                                                                    |
| [Lehrbuch](https://w3id.org/kim/hcrt/textbook)              | ❓                                                                                                                                                    |
| [Arbeitsmaterial](https://w3id.org/kim/hcrt/worksheet)      | ❓                                                                                                                                                    |
| ❓                                                          | [Audiovisuelles Medium](http://w3id.org/openeduhub/vocabs/learningResourceType/audiovisual_medium)                                                    |
| ❓                                                          | [Radio/TV](http://w3id.org/openeduhub/vocabs/learningResourceType/broadcast)                                                                          |
| ❓                                                          | [Veranschaulichung](http://w3id.org/openeduhub/vocabs/learningResourceType/demonstration)                                                             |
| ❓                                                          | [Recherche-Auftrag](http://w3id.org/openeduhub/vocabs/learningResourceType/enquiry_oriented_activity)                                                 |
| ❓                                                          | [Entdeckendes Lernen](http://w3id.org/openeduhub/vocabs/learningResourceType/exploration)                                                             |
| ❓                                                          | [Modell](http://w3id.org/openeduhub/vocabs/learningResourceType/model)                                                                                |
| ❓                                                          | [Offene Aktivität](http://w3id.org/openeduhub/vocabs/learningResourceType/open_activity)                                                              |
| ❓                                                          | [Projekt](http://w3id.org/openeduhub/vocabs/learningResourceType/project)                                                                             |
| ❓                                                          | [Primärmaterial/Quelle](http://w3id.org/openeduhub/vocabs/learningResourceType/reference)                                                             |
| ❓                                                          | [Rollenspiel](http://w3id.org/openeduhub/vocabs/learningResourceType/role_play)                                                                       |
| ❓                                                          | [Unterrichtsbaustein](http://w3id.org/openeduhub/vocabs/learningResourceType/teaching_module)                                                         |
| ❓                                                          | [Werkzeug](http://w3id.org/openeduhub/vocabs/learningResourceType/tool)                                                                               |
| ❓                                                          | [Weblog](http://w3id.org/openeduhub/vocabs/learningResourceType/weblog)                                                                               |
| ❓                                                          | [Wiki](http://w3id.org/openeduhub/vocabs/learningResourceType/wiki)                                                                                   |
| ❓                                                          | [Andere Web Ressource](http://w3id.org/openeduhub/vocabs/learningResourceType/other_web_resource)                                                     |

**Comment by MRuecklCC** [comment]
What does HCRT stand for? Is this a vocabulary from a third party? How were connections to external SKOs systems handled in the past? @sroertgen @torsten-simon 

Wikipedia gives some info about inter concept schema relations ([here](https://en.wikipedia.org/wiki/Simple_Knowledge_Organization_System#Element_categories) and [here](https://en.wikipedia.org/wiki/Simple_Knowledge_Organization_System#Semantic_relations)).

I would argue, that for e.g. "Sonstiges" where there is no 1:1 relation in the above table a different relation type is used (maybe `relatedMatch`?) whereas for stuff like `Karte` it would be an `exactMatch

**Comment by lummerland** [comment]
> What does HCRT stand for? Is this a vocabulary from a third party? How were connections to external SKOs systems handled in the past? @sroertgen @torsten-simon

HCRT stands for "Hochschulcampus Ressourcetypen" (https://skohub.io/dini-ag-kim/hcrt/heads/master/w3id.org/kim/hcrt/scheme.de.html). This vocab is used in "Allgemeines Metadatenprofil für Bildungsressourcen" (AMB -> https://dini-ag-kim.github.io/amb/draft/#learningresourcetype) which is used by OERSI.

**Comment by MRuecklCC** [comment]
Not sure why and how to fix it, but when I open it in pycharm it complains that it cannot load the hcrt prefix:
image

I saw this in other files as well, where some of the prefixes seem to be broken. Maybe its an issue with the PyCharm plugin thou!

**Comment by MRuecklCC** [comment]
Ahh, played around with it a little more: If I change the prefix to `@prefix hcrt: <https://w3id.org/kim/hcrt/> .` And download the respective ttl file from https://raw.githubusercontent.com/dini-ag-kim/hcrt/master/hcrt.ttl. Then add it in the pycharm plugin config, it works, I can actually jump between the concept schemas by CTRL+Click on the `skos:exactMatch hcrt:application ;` blocks.

image

**Comment by sroertgen** [comment]
> I played around even further: When I use `@prefix hcrt: <https://w3id.org/kim/hcrt/scheme> .` The syntax highlighting does not complain about the prefix definition, and I can CTRL-click jump to the hcrt file. However, then it does not pick up the match relations any more: image That seems to be some namespace issue. In the ttl files of this repository the toplevel concept schema use empty ids (i.e. `<> a skos:ConceptScheme;`) if i change the `hcrt.ttl` file accordingly both the warnings about the namespace and the warnings for references concepts disapear.

Yes. Though it is totally valid to use a dedicated namespace to indicate the ConceptScheme (e.g. `<scheme>`), it is more or less a best practice to use an empty id, i.e. the URL for the prefix.

**Comment by sroertgen** [comment]
> This is a comparison of all concepts as far as I can tell. How do we handle missing matches?

Thanks. Looks good to me. I think whereever we don't have an appropriate match, we will not map. This way we don't blew up the "other" category too much. Also, in case we add a new learning resource type, we can then add a mapping and can crawl again. Let's talk it through in the conference this evening and merge is afterwards if there is no complaint

**Comment by MRuecklCC** [comment]
We could raise an issue on [their repo](https://github.com/dini-ag-kim/hcrt) to follow that best practice :-)

**Comment by sroertgen** [comment]
> We could raise an issue on [their repo](https://github.com/dini-ag-kim/hcrt) to follow that best practice :-)

Since their vocabulary is already published, that would change their URIs, but [Cool URIs don't change](https://www.w3.org/Provider/Style/URI.html). Well, would at least require a redirect, I guess

**Comment by lummerland** [comment]
> > We could raise an issue on [their repo](https://github.com/dini-ag-kim/hcrt) to follow that best practice :-)
> 
> Since their vocabulary is already published, that would change their URIs, but [Cool URIs don't change](https://www.w3.org/Provider/Style/URI.html). Well, would at least require a redirect, I guess

Maybe we should hand out the w3 document to some providers of learning resources ... :smile:

**Pull request merged**
